name: codecov
on: 
  pull_request:

jobs:
  run-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: test
          files: ./coverage/*.json
          verbose: true
      
      - name: Comment on PR with Codecov information
        run: |
          bash <(curl -s https://codecov.io/bash) -f coverage/*.json -F test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}