name: codecov
on:
  pull_request:

jobs:
  run-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install jest

      - name: Run Jest tests
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        # with:
        #   files: ./coverage/coverage-final.json
        #   flags: unit
        #   fail_ci_if_error: ${{ github.repository == 'jiji14/mood-tracker' }}
