name: codecov
on: 
  pull_request:

jobs:
  run-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./path/to/coverage/*.json
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need
          
      - name: Comment on PR with Codecov information
        run: |
          bash <(curl -s https://codecov.io/bash) -f coverage/*.json -F test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}